/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_marioia;

import javax.swing.ImageIcon;

/**
 *
 * @author luisg
 */
public class PanelFinalJuego extends javax.swing.JFrame {

    /**
     * Creates new form PanelFinalJuego
     */
    public PanelFinalJuego(String Personaje) {
        initComponents();
        this.setResizable(false);
        this.setSize(400, 350);
        this.setVisible(true);
        if (Personaje =="Mario"){
        this.Etiqueta.setIcon(new ImageIcon("src\\Resource\\Imagens\\Tags\\Game Over-Mario.gif"));
        }
        if (Personaje =="Luigi"){
        this.Etiqueta.setIcon(new ImageIcon("src\\Resource\\Imagens\\Tags\\Game Over-Luigi.gif"));}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Etiqueta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(Etiqueta);
        Etiqueta.setBounds(-50, -10, 480, 330);

        pack();
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Etiqueta;
    // End of variables declaration//GEN-END:variables
}
